export const LOAD_ACCOUNTS = '[ACCOUNT] LOAD_ACCOUNTS';
export const CREATE_ACCOUNT = '[ACCOUNT] CREATE_ACCOUNT';
export const GET_ID_ACCOUNT = '[ACCOUNT] GET_ID_ACCOUNT';
export const UPDATE_ACCOUNT = '[ACCOUNT] UPDATE_ACCOUNT';
export const PATCH_ACCOUNT = '[ACCOUNT] PATCH_ACCOUNT';
export const DELETE_ACCOUNT = '[ACCOUNT] DELETE_ACCOUNT';
export const HIDE_LOADER = '[ACCOUNT] HIDE_LOADER';
export const SHOW_LOADER = '[ACCOUNT] SHOW_LOADER';
