export const LOAD_USER = '[USER] LOAD_USER';
export const UPDATE_USER_SUCESSFUL = '[USER] UPDATE_USER_SUCESSFUL';
export const UPDATE_USER_FAILURE = '[USER] UPDATE_USER_FAILURE';
export const UPLOAD_USER_PICTURE = '[USER] UPLOAD_USER_PICTURE';
